### ISSUE TITLE
Server crashing when interacting with the easel.

### ISSUE THREAD

**Issue by Scheremy** [thelegitdolt/easel-does-it-2#3]
Multiplayer world/server crashes when interacting with the easel with or without an item in hand.
_Interacting with the easel in Singleplayer, with the same world, same mods, and in the same place works fine._

Log:
[2024-10-19-2.log](https://github.com/user-attachments/files/17447363/2024-10-19-2.log)

Mod List:

- Amendments
- Aquaculture
- Architectury
- Armor Statues
- Artifacts
- Arts & Crafts/Compat
- Bad Packets
- Blueprint
- Bountiful Fares
- Built
- Buzzier Bees
- Call Of Yucatan
- Canary
- Carry On
- Citadel
- Clayworks
- Cloth Config
- Cluttered
- Comforts
- **Sinytra Connector**
- Corgi Lib
- CoroUtil
- Cosmetic Armor Reworked
- Create
- Critters And Companions
- Croptopia
- Curios
- Dye Depot
- Easel Does It
- Embeddium
- Entity Culling
- EpheroLib
- Etcetera
- Exposure
- Fabric Api
- Falling Tree
- Farmer's Delight
- Fast Config Api
- Ferrite Core
- Framework
- Geckolib
- Ice & Fire: Dragons
- Jade
- JEI
- Just Leveling
- Labelling Containers
- Let Me Despawn
- Let's Do API/Furniture/Bakery/Beach Party
- LootR
- Memory Leak Fix
- Minecraft Comes Alive
- Moonlight
- Noisium
- Obscure API
- Overweight Farming
- Plushie Buddies
- Polymorph
- Portfolio
- PuzzlesLib
- Quark
- Redwolf Music Expansion
- Refurbished Furniture
- Ribbits
- Searchables
- ServerCore
- Sophisticated Backpacks/Core
- Spark
- Supplementaries/Squared
- Tectonic
- Vanity (Aesthetic Armory/Colossal Weapons)
- Warden Tools
- Xaero's Minimap/Worldmap
- Yet Another Config Lib
- Yung's API
- Zeta

**Comment by thelegitdolt** [comment]
wtf

**Comment by thelegitdolt** [comment]
okay fixed new update is out tell me if it works

**Comment by Scheremy** [comment]
> okay fixed new update is out tell me if it works

Works just fine now, thank you :)
